### PR TITLE
Cisco snmp copy config

### PR DESCRIPTION
**Pull request by jimnagy**
I took the existing cisco_snmp_save_config module and created a more generic version that I named cisco_snmp_copy_config.  This allows one to copy a running or startup config to or from a tftp server, in addition to supporting a copy run start.  We plan to use this to load dynamically generated base configs onto our IOS devices.  I haven't thoroughly tested it yet, but it seems to work well for copying a config from our tftp server to a router.  This new module also requires a quick change to nelsnmp to add the extra OID's needed to support tftp options.

### CODE REVIEW

**Comment by ogenstad** [comment]
Hi Jim,

Thank you for the contribution! My plan was to release a module like this which is separate from the other module which only saves the configuration.

One issue with the documentation:
+author: Patrick Ogenstad (@networklore)
+author: Jim Nagy (@jimnagy)

I don't think this is currently used but it would be better to just have one entry for both names comma separated. I don't care which of us comes first. 

What I would like to change is the tftp_ip parameter. Since ccCopyProtocol also support scp, ftp, sftp and rcp I think it would be better with a more generic parameter. Perhaps just "server" would be better. The ccCopyServerAddress oid has been deprecated in favor of ccCopyServerAddressRev1 which supports IPv4, IPv6 and DNS hosts. Using this oid also requires you to set ccCopyServerAddressType. What I was thinking was that ccCopyServerAddressType would default to IPv4 but could be changed with a server_addresstype parameter (or perhaps a better name).

I haven't tested using ccCopyServerAddressRev1 myself and I don't think an initial version of this module needs to use it. However if I or someone else wants to add support for other protocols I don't want to add additional parameters or change the existing ones. So I would like to move away from tftp_ip to a parameter which could accept an address IPv4/6 or DNS name. Changing this would make sure that peoples Playbooks don't have to be changed for future versions.

What do you think about this change?

I released a new version of nelsnmp to pypi and also added some more oids from CISCO-CONFIG-COPY-MIB.

Best regards
Patrick

**Comment by jimnagy** [comment]
Sounds good to me.  I'll make the changes and test it out on Monday.

Thanks for the feedback.
-Jim

**Comment by jimnagy** [comment]
For now I just changed the parameter from tftp_ip to server.  Support for other copy protocols and the newer OID can be added in the future if someone needs them.

**Comment by ogenstad** [comment]
Thanks that sounds good and thanks again for your contribution. I might do some small modifications to the code later but nothing which will change the playbooks.

**Pull request merged**
